apiVersion: v1
kind: Service
metadata: 
  name: linux-sandbox
  namespace: linux-sandbox
  annotations: 
    # attach ACM SSL certification to our classic load balancer (CLB) service
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:705738638798:certificate/29234ef0-e457-4334-9f8d-5b954c71bd4b"
    # public port 443 configuration for CLB
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # idle timeout 
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"

spec:
  selector:
    app: linux-sandbox
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80              # expose port 80
    targetPort: 7681
  - name: https 
    protocol: TCP         
    port: 443             # expose port 443
    targetPort: 7681
